### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by TheMeGaMaN** [l-t-s/LongTermSupport#1]
how do i install "free minecraft infinite diamonds hack" for my console version pls help i dont now what do there no answer in 4chan only call me noobkid pls halp i only got 0.10€ so u can have it if u teach me senpai
my specs are:
razer mouse
logitech keyboard
some headset that came free with my console

**Comment by l-t-s** [comment]
U need to fry ur laptop in microwav
if u dont hav microwav or laptop pls dont sue me
